#!/bin/bash
set -e

# Email Server Docker Entrypoint
# ===============================

CONFIG_FILE="/etc/email_server/server.conf"
CERT_DIR="/etc/ssl/email_server"
DB_FILE="/var/lib/email_server/users.db"

# Default values from environment
MAIL_DOMAIN="${MAIL_DOMAIN:-example.com}"
MAIL_HOSTNAME="${MAIL_HOSTNAME:-mail.${MAIL_DOMAIN}}"
SERVER_IP="${SERVER_IP:-0.0.0.0}"

echo "=========================================="
echo "Email Server Starting"
echo "=========================================="
echo "Domain: ${MAIL_DOMAIN}"
echo "Hostname: ${MAIL_HOSTNAME}"
echo "Server IP: ${SERVER_IP}"
echo ""

# Generate configuration if not exists
generate_config() {
    if [ ! -f "$CONFIG_FILE" ]; then
        echo "Generating configuration file..."
        cat > "$CONFIG_FILE" << EOF
# Email Server Configuration
# Generated by Docker entrypoint

[tls]
certificate = ${CERT_DIR}/server.crt
private_key = ${CERT_DIR}/server.key
ca_file = ${CERT_DIR}/ca.crt

[database]
path = ${DB_FILE}

[storage]
maildir_root = /var/mail
default_quota = ${DEFAULT_QUOTA:-104857600}
create_directories = true

[log]
level = ${LOG_LEVEL:-info}
console = true
file = /var/log/email_server/server.log

[smtp]
bind_address = 0.0.0.0
port = 25
tls_port = 465
hostname = ${MAIL_HOSTNAME}
max_connections = ${MAX_CONNECTIONS:-1000}
max_message_size = ${MAX_MESSAGE_SIZE:-26214400}
max_recipients = ${MAX_RECIPIENTS:-100}
require_auth = ${SMTP_REQUIRE_AUTH:-true}
enable_starttls = true
allow_relay = ${SMTP_ALLOW_RELAY:-false}
local_domains = ${MAIL_DOMAIN}, ${MAIL_HOSTNAME}

[pop3]
bind_address = 0.0.0.0
port = 110
tls_port = 995
max_connections = ${MAX_CONNECTIONS:-500}
enable_starttls = true

[imap]
bind_address = 0.0.0.0
port = 143
tls_port = 993
max_connections = ${MAX_CONNECTIONS:-500}
enable_starttls = true
enable_idle = true
EOF
        echo "Configuration generated at ${CONFIG_FILE}"
    else
        echo "Using existing configuration at ${CONFIG_FILE}"
    fi
}

# Generate SSL certificates if not exists
generate_certs() {
    if [ ! -f "${CERT_DIR}/server.crt" ] || [ ! -f "${CERT_DIR}/server.key" ]; then
        echo "Generating SSL certificates..."
        /usr/local/bin/generate_certs.sh "${MAIL_HOSTNAME}" "${CERT_DIR}"
        echo "Certificates generated in ${CERT_DIR}"
    else
        echo "Using existing certificates in ${CERT_DIR}"
    fi
}

# Initialize database and create admin user if needed
init_database() {
    if [ ! -f "$DB_FILE" ]; then
        echo "Initializing database..."

        # Create a temporary user to initialize the database
        /usr/local/bin/create_user -d "$DB_FILE" domain add "${MAIL_DOMAIN}" 2>/dev/null || true

        # Create admin user if credentials provided
        if [ -n "$ADMIN_EMAIL" ] && [ -n "$ADMIN_PASSWORD" ]; then
            echo "Creating admin user: ${ADMIN_EMAIL}"
            echo -e "${ADMIN_PASSWORD}\n${ADMIN_PASSWORD}" | \
                /usr/local/bin/create_user -d "$DB_FILE" -m /var/mail add "${ADMIN_EMAIL}"
        fi

        echo "Database initialized at ${DB_FILE}"
    else
        echo "Using existing database at ${DB_FILE}"
    fi
}

# Set proper permissions
set_permissions() {
    chown -R mail:mail /var/mail 2>/dev/null || true
    chown -R mail:mail /var/lib/email_server 2>/dev/null || true
    chown -R mail:mail /var/log/email_server 2>/dev/null || true
    chmod 600 ${CERT_DIR}/*.key 2>/dev/null || true
}

# Health check function
health_check() {
    # Check if servers are responding
    nc -z localhost 25 && nc -z localhost 110 && nc -z localhost 143
}

# Start all services
start_all() {
    echo "Starting all email services..."

    # Start SMTP server in background
    echo "Starting SMTP server..."
    /usr/local/bin/smtp_server -c "$CONFIG_FILE" &
    SMTP_PID=$!

    # Start POP3 server in background
    echo "Starting POP3 server..."
    /usr/local/bin/pop3_server -c "$CONFIG_FILE" &
    POP3_PID=$!

    # Start IMAP server in background
    echo "Starting IMAP server..."
    /usr/local/bin/imap_server -c "$CONFIG_FILE" &
    IMAP_PID=$!

    echo ""
    echo "=========================================="
    echo "All services started!"
    echo "=========================================="
    echo "SMTP:  Port 25 (plain), 465 (TLS), 587 (submission)"
    echo "POP3:  Port 110 (plain), 995 (TLS)"
    echo "IMAP:  Port 143 (plain), 993 (TLS)"
    echo ""
    echo "PIDs: SMTP=$SMTP_PID, POP3=$POP3_PID, IMAP=$IMAP_PID"
    echo ""

    # Handle shutdown signals
    trap "echo 'Shutting down...'; kill $SMTP_PID $POP3_PID $IMAP_PID 2>/dev/null; exit 0" SIGTERM SIGINT

    # Wait for any process to exit
    wait -n $SMTP_PID $POP3_PID $IMAP_PID

    # If we get here, a process died
    echo "A service has stopped. Shutting down all services..."
    kill $SMTP_PID $POP3_PID $IMAP_PID 2>/dev/null
    exit 1
}

# Main execution
case "${1:-all}" in
    smtp)
        generate_config
        generate_certs
        init_database
        set_permissions
        echo "Starting SMTP server only..."
        exec /usr/local/bin/smtp_server -c "$CONFIG_FILE"
        ;;
    pop3)
        generate_config
        generate_certs
        init_database
        set_permissions
        echo "Starting POP3 server only..."
        exec /usr/local/bin/pop3_server -c "$CONFIG_FILE"
        ;;
    imap)
        generate_config
        generate_certs
        init_database
        set_permissions
        echo "Starting IMAP server only..."
        exec /usr/local/bin/imap_server -c "$CONFIG_FILE"
        ;;
    all)
        generate_config
        generate_certs
        init_database
        set_permissions
        start_all
        ;;
    init)
        generate_config
        generate_certs
        init_database
        set_permissions
        echo "Initialization complete."
        ;;
    create-user)
        shift
        exec /usr/local/bin/create_user -d "$DB_FILE" -m /var/mail "$@"
        ;;
    shell|bash)
        exec /bin/bash
        ;;
    *)
        echo "Usage: $0 {all|smtp|pop3|imap|init|create-user|shell}"
        exit 1
        ;;
esac
